/*
 * xquest.h - XQuest 2 for Sega Genesis (SGDK 1.70)
 * Global definitions, types and constants
 */

#ifndef XQUEST_H
#define XQUEST_H

#include <genesis.h>

/* ============================================================
 * SCREEN / DISPLAY
 * ============================================================ */
#define SCREEN_W            320
#define SCREEN_H            224     /* Genesis native (cropped from original 240) */
#define PLAYFIELD_W         320
#define PLAYFIELD_H         208     /* minus HUD bar top+bottom */
#define HUD_HEIGHT           16

/* Tile dimensions */
#define TILE_W               16
#define TILE_H               16
#define MAP_TILES_W          20     /* 320 / 16 */
#define MAP_TILES_H          13     /* 208 / 16 */

/* ============================================================
 * GAME CONSTANTS (preserved from original)
 * ============================================================ */
#define MAX_GEMS             64
#define MAX_ENEMIES          24
#define MAX_BULLETS          32
#define MAX_MINES            20
#define MAX_POWERCHARGES      4
#define MAX_EXPLOSIONS       16

#define SCORE_EXTRA_LIFE_BASE  15000   /* first extra life at 15k pts */
#define INITIAL_LIVES            3
#define MAX_SMARTBOMBS           9

/* Ship physics (8-direction, inertia-based) */
#define SHIP_ACCEL             (FIX16(0.18))
#define SHIP_MAX_SPEED         (FIX16(3.5))
#define SHIP_FRICTION          (FIX16(0.88))
#define SHIP_FIRE_COOLDOWN      6    /* frames between shots */
#define BULLET_SPEED           (FIX16(5.0))

/* Enemy counts grow with level */
#define DIFFICULTY_SCALE(lvl)  (MIN((lvl) / 5, 4))

/* ============================================================
 * PALETTE INDICES
 * ============================================================ */
#define PAL_BG        PAL0    /* background tiles */
#define PAL_ACTIVE    PAL1    /* player, bullets, mines */
#define PAL_COLLECT   PAL2    /* gems, gate, powerups */
#define PAL_ENEMY     PAL3    /* enemies, fx */

/* ============================================================
 * SPRITE TILE INDICES (set by rescomp) - forward declarations */
extern const SpriteDefinition spr_ship;
extern const SpriteDefinition spr_ship_thrust;
extern const SpriteDefinition spr_ship_diag;
extern const SpriteDefinition spr_gem;
extern const SpriteDefinition spr_mine;
extern const SpriteDefinition spr_gate;
extern const SpriteDefinition spr_powercharge;
extern const SpriteDefinition spr_smartbomb;
extern const SpriteDefinition spr_explosion;
extern const SpriteDefinition spr_bullet_player;
extern const SpriteDefinition spr_bullet_green;
extern const SpriteDefinition spr_bullet_yellow;
extern const SpriteDefinition spr_meeby;
extern const SpriteDefinition spr_grunger;
extern const SpriteDefinition spr_zippo;
extern const SpriteDefinition spr_tribbler;
extern const SpriteDefinition spr_retaliator;
extern const SpriteDefinition spr_terrier;
extern const SpriteDefinition spr_sticktight;
extern const SpriteDefinition spr_doinger;
extern const SpriteDefinition spr_vince;
extern const SpriteDefinition spr_miner;

/* SFX data arrays and sizes (generated by rescomp WAV) */
extern const u8 sfx_0[];  extern u32 sfx_0_size;
extern const u8 sfx_1[];  extern u32 sfx_1_size;
extern const u8 sfx_2[];  extern u32 sfx_2_size;
extern const u8 sfx_3[];  extern u32 sfx_3_size;
extern const u8 sfx_4[];  extern u32 sfx_4_size;
extern const u8 sfx_5[];  extern u32 sfx_5_size;
extern const u8 sfx_6[];  extern u32 sfx_6_size;
extern const u8 sfx_7[];  extern u32 sfx_7_size;
extern const u8 sfx_8[];  extern u32 sfx_8_size;

/* ============================================================
 * UTILITY MACROS
 * ============================================================ */
#ifndef MIN
#define MIN(a, b)   ((a) < (b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a, b)   ((a) > (b) ? (a) : (b))
#endif

/* fix16Abs - SGDK 1.70 does not expose this name directly */
#ifndef fix16Abs
#define fix16Abs(v)  ((v) < 0 ? -(v) : (v))
#endif

/* FIX16_FROM_FLOAT - scale a small integer expression to fix16.
 * SGDK targets the M68000 which has no FPU. We avoid runtime floats entirely.
 * Usage: FIX16_FROM_INT_SCALED(numerator, denominator)
 * e.g.  FIX16_FROM_INT_SCALED(n, 1000) converts n/1000 to fix16.
 * For the random-velocity pattern used in enemy.c:
 *   (random() % 200 - 100) * 0.015  =>  (random() % 200 - 100) * 15 / 1000
 */
#define FIX16_FROM_FRAC(num, den)   ((fix16)((s32)(num) * 65536L / (den)))

/* ============================================================
 * GLOBAL FRAME COUNTER
 * Incremented once per frame in main.c game_run().
 * ============================================================ */
extern u32 g_frame_count;

/* ============================================================
 * 8-DIRECTION VELOCITY TABLES
 * Defined in player.c, shared with enemy.c via this extern.
 * ============================================================ */
extern const fix16 DIR_DVX[8];
extern const fix16 DIR_DVY[8];

/* ============================================================
 * TYPES
 * ============================================================ */

typedef enum {
    DIR_RIGHT = 0,
    DIR_UP_RIGHT,
    DIR_UP,
    DIR_UP_LEFT,
    DIR_LEFT,
    DIR_DOWN_LEFT,
    DIR_DOWN,
    DIR_DOWN_RIGHT,
    DIR_NONE = -1
} Direction;

typedef enum {
    ENEMY_GRUNGER = 0,
    ENEMY_ZIPPO,
    ENEMY_ZINGER,
    ENEMY_VINCE,
    ENEMY_MINER,
    ENEMY_MEEBY,
    ENEMY_RETALIATOR,
    ENEMY_TERRIER,
    ENEMY_DOINGER,
    ENEMY_SNIPE,
    ENEMY_TRIBBLER,
    ENEMY_BUCKSHOT,
    ENEMY_CLUSTER,
    ENEMY_STICKTIGHT,
    ENEMY_REPULSOR,
    ENEMY_TYPE_COUNT
} EnemyType;

typedef enum {
    STATE_TITLE,
    STATE_GAME,
    STATE_PAUSED,
    STATE_LEVEL_CLEAR,
    STATE_GAME_OVER,
    STATE_HALL_OF_FAME
} GameState;

typedef struct {
    fix16 x, y;            /* position (fixed-point) */
    fix16 vx, vy;          /* velocity */
    Direction dir;         /* current movement direction */
    u8    lives;
    u8    smartbombs;
    u32   score;
    u16   shoot_cooldown;
    u8    invincible;      /* frames of post-death invincibility */
    u8    active;
    Sprite *spr;
} Player;

typedef struct {
    fix16 x, y;
    fix16 vx, vy;
    EnemyType type;
    s16   hp;
    u8    active;
    u8    anim_frame;
    u16   anim_timer;
    u16   ai_timer;        /* general-purpose AI state counter */
    u8    ai_state;
    Sprite *spr;
} Enemy;

typedef struct {
    fix16 x, y;
    fix16 vx, vy;
    u8    active;
    u8    is_player;       /* TRUE = player bullet, FALSE = enemy bullet */
    Sprite *spr;
} Bullet;

typedef struct {
    fix16 x, y;
    u8    active;
    u8    collected;
    Sprite *spr;
} Gem;

typedef struct {
    fix16 x, y;
    u8    active;
    u8    triggered;
    Sprite *spr;
} Mine;

typedef struct {
    fix16 x, y;
    u8    active;
    u16   lifetime;
    Sprite *spr;
} PowerCharge;

typedef struct {
    fix16 x, y;
    u8    active;
    u8    frame;
    Sprite *spr;
} Explosion;

typedef struct {
    Player      player;
    Enemy       enemies[MAX_ENEMIES];
    Bullet      bullets[MAX_BULLETS];
    Gem         gems[MAX_GEMS];
    Mine        mines[MAX_MINES];
    PowerCharge powercharges[MAX_POWERCHARGES];
    Explosion   explosions[MAX_EXPLOSIONS];

    u16  level;
    u8   gems_remaining;
    u8   gate_open;
    u16  level_timer;
    u8   difficulty;       /* 0=easy, 1=normal, 2=hard, 3=insane */
    GameState state;

    /* Tile map */
    u8   tilemap[MAP_TILES_H][MAP_TILES_W];   /* 0=floor, 1=wall */
} GameData;

/* ============================================================
 * FUNCTION DECLARATIONS (implemented in respective .c files)
 * ============================================================ */

/* main.c / game loop */
void game_init(void);
void game_run(void);

/* title.c */
void title_show(void);

/* player.c */
void player_init(Player *p, fix16 x, fix16 y);
void player_update(Player *p, GameData *gd);
void player_draw(Player *p);
void player_die(Player *p, GameData *gd);

/* enemy.c */
void enemy_spawn(Enemy *e, EnemyType type, fix16 x, fix16 y);
void enemies_update(GameData *gd);
void enemies_draw(GameData *gd);
void enemy_die(Enemy *e, GameData *gd);

/* gem.c */
void gems_init(GameData *gd, u8 count);
void gems_update(GameData *gd);
void gems_draw(GameData *gd);

/* bullet.c */
void bullet_fire(GameData *gd, fix16 x, fix16 y, fix16 vx, fix16 vy, u8 is_player);
void bullets_update(GameData *gd);
void bullets_draw(GameData *gd);

/* mine.c */
void mine_place(GameData *gd, fix16 x, fix16 y);
void mines_update(GameData *gd);
void mines_draw(GameData *gd);

/* smartbomb.c */
void smartbomb_activate(GameData *gd);

/* level.c */
void level_generate(GameData *gd, u16 level_num);
void level_check_complete(GameData *gd);
void level_next(GameData *gd);

/* collision.c */
void collision_check_all(GameData *gd);
u8   rects_overlap(fix16 ax, fix16 ay, u8 aw, u8 ah,
                   fix16 bx, fix16 by, u8 bw, u8 bh);

/* sfx.c */
void sfx_init(void);
void sfx_play(u8 sfx_id);

/* hud.c */
void hud_draw(GameData *gd);
void hud_update_score(u32 score);

/* Forward declarations for screens.h and player2.h types */
struct DifficultySettings;

#endif /* XQUEST_H */
